//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertInfo
    {
        public int ID { get; set; }
        public string what { get; set; }
        public string location { get; set; }
        public string additional { get; set; }
        public byte[] timeDate { get; set; }
    }
}
