//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class eTable
    {
        public int Eid { get; set; }
        public int pfNumber { get; set; }
        public string name { get; set; }
        public string profilePic { get; set; }
        public string sex { get; set; }
        public string dob { get; set; }
        public string bloodGroup { get; set; }
        public string contactInfo { get; set; }
        public string eContactInfo { get; set; }
        public string state { get; set; }
        public string qual { get; set; }
        public string designation { get; set; }
        public string currStationCode { get; set; }
        public string stationSixMonths { get; set; }
        public string sectionTI { get; set; }
        public string DateofApp { get; set; }
        public string DoJoinStation { get; set; }
        public string lastPME { get; set; }
        public string lastRCDate { get; set; }
        public string awards { get; set; }
        public string tiCount { get; set; }
        public string currStationName { get; set; }
        public string empLevel { get; set; }
    }
}
