//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTable
    {
        public int id { get; set; }
        public string type { get; set; }
        public string priority { get; set; }
        public string matter { get; set; }
        public Nullable<System.DateTime> timeDate { get; set; }
        public string sendTo { get; set; }
        public string pfNumber { get; set; }
        public string approved { get; set; }
        public string response { get; set; }
    }
}
