//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveTable
    {
        public int Lid { get; set; }
        public string pfNumber { get; set; }
        public System.DateTime fromDate { get; set; }
        public System.DateTime toDate { get; set; }
        public int noOfDates { get; set; }
        public int empLevel { get; set; }
        public string station { get; set; }
        public Nullable<int> verified { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public string leaveType { get; set; }
        public Nullable<int> sectionTI { get; set; }
        public string designation { get; set; }
        public string name { get; set; }
        public string reason { get; set; }
        public string byRef { get; set; }
    }
}
