//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class mailTable
    {
        public int mailID { get; set; }
        public string senderPfNumber { get; set; }
        public string mailTitle { get; set; }
        public string receverPfNumber { get; set; }
        public string mailBody { get; set; }
        public System.DateTime mtimeDate { get; set; }
        public string read { get; set; }
    }
}
