//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class newsTable
    {
        public int Nid { get; set; }
        public string imgLink { get; set; }
        public string title { get; set; }
        public string inBrief { get; set; }
        public Nullable<System.DateTime> newsTime { get; set; }
    }
}
