//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class sampleTable
    {
        public int id { get; set; }
        public string password { get; set; }
        public string dateStudent { get; set; }
        public Nullable<int> numberOfPresence { get; set; }
        public Nullable<int> threshold { get; set; }
    }
}
